module.exports = {
  purge: {
    mode: 'all',
    content: [
      "./templates/*.twig",
      "./templates/**/*.twig",
      "./plugins/*.twig",
      "./../../plugins/ctx-blocks/templates/*.twig"
    ]
  },
  theme: {
    colors:{
      default: "#eeeeee",
      black: {
        contrast: "var(--black-contrast)",
        transparent: "var(--black-transparent)",
        contrastsoft: "var(--black-soft-contrast)",
        lighter: "var(--black-lighter)",
        DEFAULT: "var(--black)",
        darker: "var(--black-darker)",
      },
      white: {
        contrast: "var(--white-contrast)",
        transparent: "var(--white-transparent)",
        contrastsoft: "var(--white-soft-contrast)",
        lighter: "var(--white-lighter)",
        DEFAULT: "var(--white)",
        darker: "var(--white-darker)",
      },
      gray: {
        contrast: "var(--gray-contrast)",
        transparent: "var(--gray-transparent)",
        contrastsoft: "var(--gray-soft-contrast)",
        lighter: "var(--gray-lighter)",
        DEFAULT: "var(--gray)",
        darker: "var(--gray-darker)",
      },
      lightgray: {
        contrast: "var(--lightgray-contrast)",
        transparent: "var(--lightgray-transparent)",
        contrastsoft: "var(--lightgray-soft-contrast)",
        lighter: "var(--lightgray-lighter)",
        DEFAULT: "var(--lightgray)",
        darker: "var(--lightgray-darker)",
      },
      darkgray: {
        contrast: "var(--darkgray-contrast)",
        transparent: "var(--darkgray-transparent)",
        contrastsoft: "var(--darkgray-soft-contrast)",
        lighter: "var(--darkgray-lighter)",
        DEFAULT: "var(--darkgray)",
        darker: "var(--darkgray-darker)",
      },
      blue: {
        contrast: "var(--blue-contrast)",
        transparent: "var(--blue-transparent)",
        contrastsoft: "var(--blue-soft-contrast)",
        lighter: "var(--blue-lighter)",
        DEFAULT: "var(--blue)",
        darker: "var(--blue-darker)",
      },
      lightblue: {
        contrast: "var(--lightblue-contrast)",
        contrastsoft: "var(--lightblue-soft-contrast)",
        transparent: "var(--lightblue-transparent)",
        lighter: "var(--lightblue-lighter)",
        DEFAULT: "var(--lightblue)",
        darker: "var(--lightblue-darker)",
      },
      darkblue: {
        contrast: "var(--darkblue-contrast)",
        contrastsoft: "var(--darkblue-soft-contrast)",
        transparent: "var(--darkblue-transparent)",
        lighter: "var(--darkblue-lighter)",
        DEFAULT: "var(--darkblue)",
        darker: "var(--darkblue-darker)",
      },
      orange: {
        contrast: "var(--orange-contrast)",
        contrastsoft: "var(--orange-soft-contrast)",
        transparent: "var(--orange-transparent)",
        lighter: "var(--orange-lighter)",
        DEFAULT: "var(--orange)",
        darker: "var(--orange-darker)",
      },
      lightorange: {
        contrast: "var(--lightorange-contrast)",
        contrastsoft: "var(--lightorange-soft-contrast)",
        transparent: "var(--lightorange-transparent)",
        lighter: "var(--lightorange-lighter)",
        DEFAULT: "var(--lightorange)",
        darker: "var(--lightorange-darker)",
      },
      darkorange: {
        contrast: "var(--darkorange-contrast)",
        contrastsoft: "var(--darkorange-soft-contrast)",
        transparent: "var(--darkorange-transparent)",
        lighter: "var(--darkorange-lighter)",
        DEFAULT: "var(--darkorange)",
        darker: "var(--darkorange-darker)",
      },
      purple: {
        contrast: "var(--purple-contrast)",
        contrastsoft: "var(--purple-soft-contrast)",
        transparent: "var(--purple-transparent)",
        lighter: "var(--purple-lighter)",
        DEFAULT: "var(--purple)",
        darker: "var(--purple-darker)",
      },
      lightpurple: {
        contrast: "var(--lightpurple-contrast)",
        contrastsoft: "var(--lightpurple-soft-contrast)",
        transparent: "var(--lightpurple-transparent)",
        lighter: "var(--lightpurple-lighter)",
        DEFAULT: "var(--lightpurple)",
        darker: "var(--lightpurple-darker)",
      },
      darkpurple: {
        contrast: "var(--darkpurple-contrast)",
        contrastsoft: "var(--darkpurple-soft-contrast)",
        transparent: "var(--darkpurple-transparent)",
        lighter: "var(--darkpurple-lighter)",
        DEFAULT: "var(--darkpurple)",
        darker: "var(--darkpurple-darker)",
      },
      green: {
        contrast: "var(--green-contrast)",
        contrastsoft: "var(--green-soft-contrast)",
        transparent: "var(--green-transparent)",
        lighter: "var(--green-lighter)",
        DEFAULT: "var(--green)",
        darker: "var(--green-darker)",
      },
      lightgreen: {
        contrast: "var(--lightgreen-contrast)",
        contrastsoft: "var(--lightgreen-soft-contrast)",
        transparent: "var(--lightgreen-transparent)",
        lighter: "var(--lightgreen-lighter)",
        DEFAULT: "var(--lightgreen)",
        darker: "var(--lightgreen-darker)",
      },
      darkgreen: {
        contrast: "var(--darkgreen-contrast)",
        contrastsoft: "var(--darkgreen-soft-contrast)",
        transparent: "var(--darkgreen-transparent)",
        lighter: "var(--darkgreen-lighter)",
        DEFAULT: "var(--darkgreen)",
        darker: "var(--darkgreen-darker)",
      },
      red: {
        contrast: "var(--red-contrast)",
        contrastsoft: "var(--red-soft-contrast)",
        transparent: "var(--red-transparent)",
        lighter: "var(--red-lighter)",
        DEFAULT: "var(--red)",
        darker: "var(--red-darker)",
      },
      lightred: {
        contrast: "var(--lightred-contrast)",
        contrastsoft: "var(--lightred-soft-contrast)",
        transparent: "var(--lightred-transparent)",
        lighter: "var(--lightred-lighter)",
        DEFAULT: "var(--lightred)",
        darker: "var(--lightred-darker)",
      },
      darkred: {
        contrast: "var(--darkred-contrast)",
        contrastsoft: "var(--darkred-soft-contrast)",
        transparent: "var(--darkred-transparent)",
        lighter: "var(--darkred-lighter)",
        DEFAULT: "var(--darkred)",
        darker: "var(--darkred-darker)",
      },
    },
    extend: {},
    fontFamily: {
      display: ['"Exo 2"', 'sans-serif'],
      body: ['"Exo 2"', 'sans-serif'],
      script: ['"Gochi Hand"', 'sans-serif'],
    },
    backdropFilter: { // DEFAULTs to {}
      'none': 'none',
      'blur': 'blur(10px)',
      'blur-20': 'blur(20px)',
      'blur-5': 'blur(5px)',
    },
    borderRadius: {
      'none': '0',
       'sm': '5px',
       DEFAULT: '0.25rem',
       DEFAULT: '10px',
       'md': '20px',
       'lg': '50px',
       'full': '9999px',
       'large': '12px',
    }
  },
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDEFAULT: true
  },
  variants: {
    borderRadius: ['responsive', 'last', 'first', 'hover', 'focus'],
  },
  plugins: [
    require('@tailwindcss/typography'),
  ]
}
